# DATABASE
spring:
  config:
    activate:
      on-profile: develop

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://3.39.47.51:5432/sbb
    username: sbb
    password: 1234

  jpa:
    database: postgresql
    properties:
      format_sql: true
      show_sql: true  # 콘솔에서 실행된 SQL 확인