CREATE TABLE SITE_USER
(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
);

CREATE TABLE QUESTION
(
    ID SERIAL PRIMARY KEY,
    SUBJECT VARCHAR(200) NOT NULL,
    CONTEXT TEXT NOT NULL,
    CREATE_DATE IMESTAMP NOT NULL,
    AUTHOR_ID INT,
    MODITFYDATE  IMESTAMP NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES SiteUser(ID)
);

CREATE TABLE  ANSWER
(
    ID SERIAL PRIMARY KEY,
    CONTEXT TEXT NOT NULL,
    CREATE_DATE IMESTAMP NOT NULL,
    QUSETION_ID INT,
    AUTHOR_ID INT,
    MODITFY_DATE  IMESTAMP NOT NULL,
    FOREIGN KEY (QUSETION_ID) REFERENCES Question(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES SiteUser(ID)
);
