CREATE TABLE SITE_USER
(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE  NOT NULL,
    PASSWORD VARCHAR(256)         NOT NULL,
    EMAIL    VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE QUESTION
(
    ID          SERIAL PRIMARY KEY,
    SUBJECT     VARCHAR(200) NOT NULL,
    CONTENT     TEXT         NOT NULL,
    CREATE_DATE TIMESTAMP    NOT NULL,
    AUTHOR_ID   INT,
    MODIFY_DATE TIMESTAMP    NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES SITE_USER (ID)
);

CREATE TABLE ANSWER
(
    ID          SERIAL PRIMARY KEY,
    CONTENT     TEXT      NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    QUESTION_ID INT,
    AUTHOR_ID   INT,
    MODIFY_DATE TIMESTAMP NOT NULL,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES SITE_USER (ID)
);

CREATE TABLE QUESTION_VOTER
(
    QUESTION_ID   SERIAL PRIMARY KEY,
    AUTHOR_ID     INT,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES SITE_USER (ID)
);

CREATE TABLE ANSWER_VOTER
(
    ANSWER_ID   SERIAL PRIMARY KEY,
    AUTHOR_ID     INT,
    FOREIGN KEY (ANSWER_ID) REFERENCES ANSWER (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES SITE_USER (ID)
);